; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	F:\codes\pecker_framework_git\pecker_src\pecker_framework\render\render_system\pecker_texture.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?get_frame_buffer_object_type@Ipecker_texture@pecker_sdk@@UBEIXZ ; pecker_sdk::Ipecker_texture::get_frame_buffer_object_type
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
;	COMDAT rtc$TMZ
; File f:\codes\pecker_framework_git\pecker_src\pecker_framework\render\render_system\pecker_texture.cpp
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu /ZI
rtc$IMZ	ENDS
;	COMDAT ?get_frame_buffer_object_type@Ipecker_texture@pecker_sdk@@UBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?get_frame_buffer_object_type@Ipecker_texture@pecker_sdk@@UBEIXZ PROC ; pecker_sdk::Ipecker_texture::get_frame_buffer_object_type, COMDAT
; _this$ = ecx

; 15   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 16   : 	return TEXTURE_BUFFER_TYPE;

	mov	eax, 3

; 17   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?get_frame_buffer_object_type@Ipecker_texture@pecker_sdk@@UBEIXZ ENDP ; pecker_sdk::Ipecker_texture::get_frame_buffer_object_type
_TEXT	ENDS
PUBLIC	?get_texture_type@Ipecker_texture2d@pecker_sdk@@UBEIXZ ; pecker_sdk::Ipecker_texture2d::get_texture_type
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?get_texture_type@Ipecker_texture2d@pecker_sdk@@UBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?get_texture_type@Ipecker_texture2d@pecker_sdk@@UBEIXZ PROC ; pecker_sdk::Ipecker_texture2d::get_texture_type, COMDAT
; _this$ = ecx

; 20   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 21   : 	return TEXTURE_2D_TYPE;

	mov	eax, 1

; 22   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?get_texture_type@Ipecker_texture2d@pecker_sdk@@UBEIXZ ENDP ; pecker_sdk::Ipecker_texture2d::get_texture_type
_TEXT	ENDS
PUBLIC	?get_texture_type@Ipecker_texture_cube@pecker_sdk@@UBEIXZ ; pecker_sdk::Ipecker_texture_cube::get_texture_type
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?get_texture_type@Ipecker_texture_cube@pecker_sdk@@UBEIXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?get_texture_type@Ipecker_texture_cube@pecker_sdk@@UBEIXZ PROC ; pecker_sdk::Ipecker_texture_cube::get_texture_type, COMDAT
; _this$ = ecx

; 25   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	mov	ecx, 51					; 00000033H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 26   : 	return TEXTURE_CUBE_TYPE;

	mov	eax, 2

; 27   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?get_texture_type@Ipecker_texture_cube@pecker_sdk@@UBEIXZ ENDP ; pecker_sdk::Ipecker_texture_cube::get_texture_type
_TEXT	ENDS
END
